INSERT INTO "ENTITY_LEVEL" ("ENTITY_LEVEL_ID", "LEVEL_NO", "LEVEL_TITLE", "ENTITY_TYPE") VALUES (4, 1, 'level-1', 0);
INSERT INTO "ENTITY_LEVEL" ("ENTITY_LEVEL_ID", "LEVEL_NO", "LEVEL_TITLE", "ENTITY_TYPE") VALUES (1, 0, 'Basic', 1);
INSERT INTO "ENTITY_LEVEL" ("ENTITY_LEVEL_ID", "LEVEL_NO", "LEVEL_TITLE", "ENTITY_TYPE") VALUES (2, 0, 'Basic', 0);
