INSERT INTO "WORD_GROUP" ("WORD_GROUP_ID", "TITLE", "LEVEL_ID") VALUES (12345, 'seasonsname', 4);
INSERT INTO "WORD_GROUP" ("WORD_GROUP_ID", "TITLE", "LEVEL_ID") VALUES (1000002, 'adcas', 4);
INSERT INTO "WORD_GROUP" ("WORD_GROUP_ID", "TITLE", "LEVEL_ID") VALUES (1, 'e', 2);
INSERT INTO "WORD_GROUP" ("WORD_GROUP_ID", "TITLE", "LEVEL_ID") VALUES (2, 'fruitname', 2);
