INSERT INTO "WORD" ("ENTITY_ID", "WORD", "MEANING", "PARTS_OF_SPEECH", "WORD_GROUP_ID") VALUES (1000029, 'new', ' fresh', 'adjective', 12345);
INSERT INTO "WORD" ("ENTITY_ID", "WORD", "MEANING", "PARTS_OF_SPEECH", "WORD_GROUP_ID") VALUES (1000049, 'Apple', 'Round, red fruit', 'Noun', 2);
INSERT INTO "WORD" ("ENTITY_ID", "WORD", "MEANING", "PARTS_OF_SPEECH", "WORD_GROUP_ID") VALUES (1000027, 'a', 'b', 'v', 1);
